server:
  port: 8081 #配置端口
  servlet:
    context-path: /message #配置访问时的项目名


spring:
  datasource:
    url: jdbc:mysql://192.168.0.130:3306/messagesql?serverTimezone=UTC&characterEncoding=utf8
    username: root
    password: 321
    driver-class-name: com.mysql.cj.jdbc.Driver
    maxActive: 20
    initialSize: 1
  jpa:
    database: mysql
#    hibernate:
#      ddl-auto: update
    show-sql: true
